version: '2'

services:
  app:
    build: app
    depends_on:
      - db
    env_file:
      - .env/app.env
      - .env/db.env
      - .env/web.env
    volumes:
      - app-data:/var/www
    volumes_from:
      - db
  db:
    image: mariadb:latest
    env_file:
      - .env/db.env
    restart: always
    volumes:
      - db-data:/var/lib/mysql
  web:
    build: web
    env_file:
      - .env/web.env
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes_from:
      - app

volumes:
  app-data:
    driver: local
  db-data:
    driver: local
